/**
 * 全局
 */
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const SERVER_ERROR = 'SERVER_ERROR';
export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const DISPLAY_SUCCESS = 'DISPLAY_ERROR';

export const GET_TREEVIEW = 'GET_TREEVIEW';
export const GET_CODE_STATUS = 'GET_CODE_STATUS';
export const GET_PROJECTS_STATUS = 'GET_PROJECTS_STATUS';
export const DO_PROJECT_DELETE = 'DO_PROJECT_DELETE';
export const DO_PROJECT_EDIT = 'DO_PROJECT_EDIT';
export const GET_TIMELINE_STATUS = 'GET_TIMELINE_STATUS';
export const GET_MEMORY_STATUS = 'GET_MEMORY_STATUS';
export const GET_RESOURCES_STATUS = 'GET_RESOURCES_STATUS';
export const GET_PV_STATUS = 'GET_PV_STATUS';
export const GET_JS_ERROR_TABLE_DATA_STATUS = 'GET_JS_ERROR_TABLE_DATA_STATUS';
export const GET_SLOW_TIMING_TABLE_DATA_STATUS = 'GET_SLOW_TIMING_TABLE_DATA_STATUS';
export const GET_BIG_MEMORY_TABLE_DATA_STATUS = 'GET_BIG_MEMORY_TABLE_DATA_STATUS';
export const DO_JS_ERROR_SOLVE = 'DO_JS_ERROR_SOLVE';

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_ROLE_DATA = 'GET_ROLE_DATA';
export const DO_USER_DELETE = 'DO_USER_DELETE';
export const DO_USER_ADD = 'DO_USER_ADD';

export const GET_CONFIG_DATA = 'GET_CONFIG_DATA';
export const DO_CONFIG_DELETE = 'DO_CONFIG_DELETE';
export const DO_CONFIG_ADD = 'DO_CONFIG_ADD';

export const GET_PAGES = 'GET_PAGES';

export const GET_DB_LIST = 'GET_DB_LIST';
export const BATCH_DB_LIST = 'BATCH_DB_LIST';
export const DO_AGGREGATE = 'DO_AGGREGATE';
